seed = 0

[data]
cat_policy = 'ohe'
dset_id = 40975
task = 'multiclass'

[fit]
early_stopping_rounds = 50
verbose = false

[model]
alpha = 0
booster = 'gbtree'
colsample_bylevel = 0.9003170369398446
colsample_bytree = 0.8375261330746506
gamma = 0
lambda = 0.3285661513461997
learning_rate = 0.1800735399314305
max_depth = 6
min_child_weight = 0.002480897001227389
n_estimators = 2000
n_jobs = -1
subsample = 0.5808291401239343
tree_method = 'gpu_hist'

[transfer]
checkpoint_path = nan
downstream_samples_per_class = nan
epochs_warm_up_head = 0
freeze_feature_extractor = false
head_lr = nan
layers_to_fine_tune = []
load_checkpoint = false
pretrain_proportion = 0.5
stage = 'pretrain'
use_mlp_head = false
