python dispatch_single_node.py launch/tuned_catboost_jobs/mimic0_catboost_mimic_exp_seed0.sh --name mimic0_catboost_mimic_exp_seed0 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic0_catboost_mimic_exp_seed1.sh --name mimic0_catboost_mimic_exp_seed1 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic0_catboost_mimic_exp_seed2.sh --name mimic0_catboost_mimic_exp_seed2 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic0_catboost_mimic_exp_seed3.sh --name mimic0_catboost_mimic_exp_seed3 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic0_catboost_mimic_exp_seed4.sh --name mimic0_catboost_mimic_exp_seed4 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic10_catboost_mimic_exp_seed0.sh --name mimic10_catboost_mimic_exp_seed0 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic10_catboost_mimic_exp_seed1.sh --name mimic10_catboost_mimic_exp_seed1 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic10_catboost_mimic_exp_seed2.sh --name mimic10_catboost_mimic_exp_seed2 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic10_catboost_mimic_exp_seed3.sh --name mimic10_catboost_mimic_exp_seed3 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic10_catboost_mimic_exp_seed4.sh --name mimic10_catboost_mimic_exp_seed4 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic11_catboost_mimic_exp_seed0.sh --name mimic11_catboost_mimic_exp_seed0 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic11_catboost_mimic_exp_seed1.sh --name mimic11_catboost_mimic_exp_seed1 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic11_catboost_mimic_exp_seed2.sh --name mimic11_catboost_mimic_exp_seed2 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic11_catboost_mimic_exp_seed3.sh --name mimic11_catboost_mimic_exp_seed3 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic11_catboost_mimic_exp_seed4.sh --name mimic11_catboost_mimic_exp_seed4 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic1_catboost_mimic_exp_seed0.sh --name mimic1_catboost_mimic_exp_seed0 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic1_catboost_mimic_exp_seed1.sh --name mimic1_catboost_mimic_exp_seed1 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic1_catboost_mimic_exp_seed2.sh --name mimic1_catboost_mimic_exp_seed2 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic1_catboost_mimic_exp_seed3.sh --name mimic1_catboost_mimic_exp_seed3 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic1_catboost_mimic_exp_seed4.sh --name mimic1_catboost_mimic_exp_seed4 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic2_catboost_mimic_exp_seed0.sh --name mimic2_catboost_mimic_exp_seed0 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic2_catboost_mimic_exp_seed1.sh --name mimic2_catboost_mimic_exp_seed1 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic2_catboost_mimic_exp_seed2.sh --name mimic2_catboost_mimic_exp_seed2 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic2_catboost_mimic_exp_seed3.sh --name mimic2_catboost_mimic_exp_seed3 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic2_catboost_mimic_exp_seed4.sh --name mimic2_catboost_mimic_exp_seed4 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic3_catboost_mimic_exp_seed0.sh --name mimic3_catboost_mimic_exp_seed0 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic3_catboost_mimic_exp_seed1.sh --name mimic3_catboost_mimic_exp_seed1 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic3_catboost_mimic_exp_seed2.sh --name mimic3_catboost_mimic_exp_seed2 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic3_catboost_mimic_exp_seed3.sh --name mimic3_catboost_mimic_exp_seed3 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic3_catboost_mimic_exp_seed4.sh --name mimic3_catboost_mimic_exp_seed4 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic4_catboost_mimic_exp_seed0.sh --name mimic4_catboost_mimic_exp_seed0 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic4_catboost_mimic_exp_seed1.sh --name mimic4_catboost_mimic_exp_seed1 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic4_catboost_mimic_exp_seed2.sh --name mimic4_catboost_mimic_exp_seed2 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic4_catboost_mimic_exp_seed3.sh --name mimic4_catboost_mimic_exp_seed3 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic4_catboost_mimic_exp_seed4.sh --name mimic4_catboost_mimic_exp_seed4 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic5_catboost_mimic_exp_seed0.sh --name mimic5_catboost_mimic_exp_seed0 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic5_catboost_mimic_exp_seed1.sh --name mimic5_catboost_mimic_exp_seed1 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic5_catboost_mimic_exp_seed2.sh --name mimic5_catboost_mimic_exp_seed2 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic5_catboost_mimic_exp_seed3.sh --name mimic5_catboost_mimic_exp_seed3 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic5_catboost_mimic_exp_seed4.sh --name mimic5_catboost_mimic_exp_seed4 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic6_catboost_mimic_exp_seed0.sh --name mimic6_catboost_mimic_exp_seed0 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic6_catboost_mimic_exp_seed1.sh --name mimic6_catboost_mimic_exp_seed1 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic6_catboost_mimic_exp_seed2.sh --name mimic6_catboost_mimic_exp_seed2 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic6_catboost_mimic_exp_seed3.sh --name mimic6_catboost_mimic_exp_seed3 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic6_catboost_mimic_exp_seed4.sh --name mimic6_catboost_mimic_exp_seed4 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic7_catboost_mimic_exp_seed0.sh --name mimic7_catboost_mimic_exp_seed0 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic7_catboost_mimic_exp_seed1.sh --name mimic7_catboost_mimic_exp_seed1 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic7_catboost_mimic_exp_seed2.sh --name mimic7_catboost_mimic_exp_seed2 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic7_catboost_mimic_exp_seed3.sh --name mimic7_catboost_mimic_exp_seed3 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic7_catboost_mimic_exp_seed4.sh --name mimic7_catboost_mimic_exp_seed4 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic8_catboost_mimic_exp_seed0.sh --name mimic8_catboost_mimic_exp_seed0 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic8_catboost_mimic_exp_seed1.sh --name mimic8_catboost_mimic_exp_seed1 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic8_catboost_mimic_exp_seed2.sh --name mimic8_catboost_mimic_exp_seed2 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic8_catboost_mimic_exp_seed3.sh --name mimic8_catboost_mimic_exp_seed3 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic8_catboost_mimic_exp_seed4.sh --name mimic8_catboost_mimic_exp_seed4 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic9_catboost_mimic_exp_seed0.sh --name mimic9_catboost_mimic_exp_seed0 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic9_catboost_mimic_exp_seed1.sh --name mimic9_catboost_mimic_exp_seed1 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic9_catboost_mimic_exp_seed2.sh --name mimic9_catboost_mimic_exp_seed2 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic9_catboost_mimic_exp_seed3.sh --name mimic9_catboost_mimic_exp_seed3 --time 72
python dispatch_single_node.py launch/tuned_catboost_jobs/mimic9_catboost_mimic_exp_seed4.sh --name mimic9_catboost_mimic_exp_seed4 --time 72
