python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic0_ft_transformer_exp_seed0.sh --name mimic0_ft_transformer_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic0_ft_transformer_exp_seed1.sh --name mimic0_ft_transformer_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic0_ft_transformer_exp_seed2.sh --name mimic0_ft_transformer_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic0_ft_transformer_exp_seed3.sh --name mimic0_ft_transformer_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic0_ft_transformer_exp_seed4.sh --name mimic0_ft_transformer_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic0_mlp_exp_seed0.sh --name mimic0_mlp_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic0_mlp_exp_seed1.sh --name mimic0_mlp_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic0_mlp_exp_seed2.sh --name mimic0_mlp_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic0_mlp_exp_seed3.sh --name mimic0_mlp_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic0_mlp_exp_seed4.sh --name mimic0_mlp_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic0_resnet_exp_seed0.sh --name mimic0_resnet_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic0_resnet_exp_seed1.sh --name mimic0_resnet_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic0_resnet_exp_seed2.sh --name mimic0_resnet_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic0_resnet_exp_seed3.sh --name mimic0_resnet_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic0_resnet_exp_seed4.sh --name mimic0_resnet_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic0_tab_transformer_exp_seed0.sh --name mimic0_tab_transformer_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic0_tab_transformer_exp_seed1.sh --name mimic0_tab_transformer_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic0_tab_transformer_exp_seed2.sh --name mimic0_tab_transformer_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic0_tab_transformer_exp_seed3.sh --name mimic0_tab_transformer_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic0_tab_transformer_exp_seed4.sh --name mimic0_tab_transformer_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic10_ft_transformer_exp_seed0.sh --name mimic10_ft_transformer_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic10_ft_transformer_exp_seed1.sh --name mimic10_ft_transformer_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic10_ft_transformer_exp_seed2.sh --name mimic10_ft_transformer_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic10_ft_transformer_exp_seed3.sh --name mimic10_ft_transformer_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic10_ft_transformer_exp_seed4.sh --name mimic10_ft_transformer_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic10_mlp_exp_seed0.sh --name mimic10_mlp_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic10_mlp_exp_seed1.sh --name mimic10_mlp_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic10_mlp_exp_seed2.sh --name mimic10_mlp_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic10_mlp_exp_seed3.sh --name mimic10_mlp_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic10_mlp_exp_seed4.sh --name mimic10_mlp_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic10_resnet_exp_seed0.sh --name mimic10_resnet_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic10_resnet_exp_seed1.sh --name mimic10_resnet_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic10_resnet_exp_seed2.sh --name mimic10_resnet_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic10_resnet_exp_seed3.sh --name mimic10_resnet_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic10_resnet_exp_seed4.sh --name mimic10_resnet_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic10_tab_transformer_exp_seed0.sh --name mimic10_tab_transformer_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic10_tab_transformer_exp_seed1.sh --name mimic10_tab_transformer_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic10_tab_transformer_exp_seed2.sh --name mimic10_tab_transformer_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic10_tab_transformer_exp_seed3.sh --name mimic10_tab_transformer_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic10_tab_transformer_exp_seed4.sh --name mimic10_tab_transformer_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic11_ft_transformer_exp_seed0.sh --name mimic11_ft_transformer_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic11_ft_transformer_exp_seed1.sh --name mimic11_ft_transformer_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic11_ft_transformer_exp_seed2.sh --name mimic11_ft_transformer_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic11_ft_transformer_exp_seed3.sh --name mimic11_ft_transformer_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic11_ft_transformer_exp_seed4.sh --name mimic11_ft_transformer_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic11_mlp_exp_seed0.sh --name mimic11_mlp_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic11_mlp_exp_seed1.sh --name mimic11_mlp_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic11_mlp_exp_seed2.sh --name mimic11_mlp_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic11_mlp_exp_seed3.sh --name mimic11_mlp_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic11_mlp_exp_seed4.sh --name mimic11_mlp_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic11_resnet_exp_seed0.sh --name mimic11_resnet_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic11_resnet_exp_seed1.sh --name mimic11_resnet_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic11_resnet_exp_seed2.sh --name mimic11_resnet_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic11_resnet_exp_seed3.sh --name mimic11_resnet_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic11_resnet_exp_seed4.sh --name mimic11_resnet_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic11_tab_transformer_exp_seed0.sh --name mimic11_tab_transformer_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic11_tab_transformer_exp_seed1.sh --name mimic11_tab_transformer_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic11_tab_transformer_exp_seed2.sh --name mimic11_tab_transformer_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic11_tab_transformer_exp_seed3.sh --name mimic11_tab_transformer_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic11_tab_transformer_exp_seed4.sh --name mimic11_tab_transformer_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic1_ft_transformer_exp_seed0.sh --name mimic1_ft_transformer_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic1_ft_transformer_exp_seed1.sh --name mimic1_ft_transformer_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic1_ft_transformer_exp_seed2.sh --name mimic1_ft_transformer_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic1_ft_transformer_exp_seed3.sh --name mimic1_ft_transformer_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic1_ft_transformer_exp_seed4.sh --name mimic1_ft_transformer_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic1_mlp_exp_seed0.sh --name mimic1_mlp_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic1_mlp_exp_seed1.sh --name mimic1_mlp_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic1_mlp_exp_seed2.sh --name mimic1_mlp_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic1_mlp_exp_seed3.sh --name mimic1_mlp_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic1_mlp_exp_seed4.sh --name mimic1_mlp_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic1_resnet_exp_seed0.sh --name mimic1_resnet_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic1_resnet_exp_seed1.sh --name mimic1_resnet_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic1_resnet_exp_seed2.sh --name mimic1_resnet_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic1_resnet_exp_seed3.sh --name mimic1_resnet_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic1_resnet_exp_seed4.sh --name mimic1_resnet_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic1_tab_transformer_exp_seed0.sh --name mimic1_tab_transformer_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic1_tab_transformer_exp_seed1.sh --name mimic1_tab_transformer_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic1_tab_transformer_exp_seed2.sh --name mimic1_tab_transformer_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic1_tab_transformer_exp_seed3.sh --name mimic1_tab_transformer_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic1_tab_transformer_exp_seed4.sh --name mimic1_tab_transformer_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic2_ft_transformer_exp_seed0.sh --name mimic2_ft_transformer_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic2_ft_transformer_exp_seed1.sh --name mimic2_ft_transformer_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic2_ft_transformer_exp_seed2.sh --name mimic2_ft_transformer_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic2_ft_transformer_exp_seed3.sh --name mimic2_ft_transformer_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic2_ft_transformer_exp_seed4.sh --name mimic2_ft_transformer_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic2_mlp_exp_seed0.sh --name mimic2_mlp_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic2_mlp_exp_seed1.sh --name mimic2_mlp_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic2_mlp_exp_seed2.sh --name mimic2_mlp_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic2_mlp_exp_seed3.sh --name mimic2_mlp_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic2_mlp_exp_seed4.sh --name mimic2_mlp_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic2_resnet_exp_seed0.sh --name mimic2_resnet_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic2_resnet_exp_seed1.sh --name mimic2_resnet_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic2_resnet_exp_seed2.sh --name mimic2_resnet_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic2_resnet_exp_seed3.sh --name mimic2_resnet_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic2_resnet_exp_seed4.sh --name mimic2_resnet_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic2_tab_transformer_exp_seed0.sh --name mimic2_tab_transformer_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic2_tab_transformer_exp_seed1.sh --name mimic2_tab_transformer_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic2_tab_transformer_exp_seed2.sh --name mimic2_tab_transformer_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic2_tab_transformer_exp_seed3.sh --name mimic2_tab_transformer_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic2_tab_transformer_exp_seed4.sh --name mimic2_tab_transformer_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic3_ft_transformer_exp_seed0.sh --name mimic3_ft_transformer_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic3_ft_transformer_exp_seed1.sh --name mimic3_ft_transformer_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic3_ft_transformer_exp_seed2.sh --name mimic3_ft_transformer_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic3_ft_transformer_exp_seed3.sh --name mimic3_ft_transformer_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic3_ft_transformer_exp_seed4.sh --name mimic3_ft_transformer_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic3_mlp_exp_seed0.sh --name mimic3_mlp_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic3_mlp_exp_seed1.sh --name mimic3_mlp_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic3_mlp_exp_seed2.sh --name mimic3_mlp_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic3_mlp_exp_seed3.sh --name mimic3_mlp_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic3_mlp_exp_seed4.sh --name mimic3_mlp_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic3_resnet_exp_seed0.sh --name mimic3_resnet_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic3_resnet_exp_seed1.sh --name mimic3_resnet_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic3_resnet_exp_seed2.sh --name mimic3_resnet_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic3_resnet_exp_seed3.sh --name mimic3_resnet_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic3_resnet_exp_seed4.sh --name mimic3_resnet_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic3_tab_transformer_exp_seed0.sh --name mimic3_tab_transformer_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic3_tab_transformer_exp_seed1.sh --name mimic3_tab_transformer_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic3_tab_transformer_exp_seed2.sh --name mimic3_tab_transformer_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic3_tab_transformer_exp_seed3.sh --name mimic3_tab_transformer_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic3_tab_transformer_exp_seed4.sh --name mimic3_tab_transformer_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic4_ft_transformer_exp_seed0.sh --name mimic4_ft_transformer_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic4_ft_transformer_exp_seed1.sh --name mimic4_ft_transformer_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic4_ft_transformer_exp_seed2.sh --name mimic4_ft_transformer_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic4_ft_transformer_exp_seed3.sh --name mimic4_ft_transformer_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic4_ft_transformer_exp_seed4.sh --name mimic4_ft_transformer_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic4_mlp_exp_seed0.sh --name mimic4_mlp_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic4_mlp_exp_seed1.sh --name mimic4_mlp_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic4_mlp_exp_seed2.sh --name mimic4_mlp_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic4_mlp_exp_seed3.sh --name mimic4_mlp_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic4_mlp_exp_seed4.sh --name mimic4_mlp_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic4_resnet_exp_seed0.sh --name mimic4_resnet_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic4_resnet_exp_seed1.sh --name mimic4_resnet_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic4_resnet_exp_seed2.sh --name mimic4_resnet_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic4_resnet_exp_seed3.sh --name mimic4_resnet_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic4_resnet_exp_seed4.sh --name mimic4_resnet_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic4_tab_transformer_exp_seed0.sh --name mimic4_tab_transformer_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic4_tab_transformer_exp_seed1.sh --name mimic4_tab_transformer_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic4_tab_transformer_exp_seed2.sh --name mimic4_tab_transformer_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic4_tab_transformer_exp_seed3.sh --name mimic4_tab_transformer_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic4_tab_transformer_exp_seed4.sh --name mimic4_tab_transformer_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic5_ft_transformer_exp_seed0.sh --name mimic5_ft_transformer_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic5_ft_transformer_exp_seed1.sh --name mimic5_ft_transformer_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic5_ft_transformer_exp_seed2.sh --name mimic5_ft_transformer_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic5_ft_transformer_exp_seed3.sh --name mimic5_ft_transformer_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic5_ft_transformer_exp_seed4.sh --name mimic5_ft_transformer_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic5_mlp_exp_seed0.sh --name mimic5_mlp_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic5_mlp_exp_seed1.sh --name mimic5_mlp_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic5_mlp_exp_seed2.sh --name mimic5_mlp_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic5_mlp_exp_seed3.sh --name mimic5_mlp_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic5_mlp_exp_seed4.sh --name mimic5_mlp_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic5_resnet_exp_seed0.sh --name mimic5_resnet_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic5_resnet_exp_seed1.sh --name mimic5_resnet_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic5_resnet_exp_seed2.sh --name mimic5_resnet_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic5_resnet_exp_seed3.sh --name mimic5_resnet_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic5_resnet_exp_seed4.sh --name mimic5_resnet_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic5_tab_transformer_exp_seed0.sh --name mimic5_tab_transformer_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic5_tab_transformer_exp_seed1.sh --name mimic5_tab_transformer_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic5_tab_transformer_exp_seed2.sh --name mimic5_tab_transformer_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic5_tab_transformer_exp_seed3.sh --name mimic5_tab_transformer_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic5_tab_transformer_exp_seed4.sh --name mimic5_tab_transformer_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic6_ft_transformer_exp_seed0.sh --name mimic6_ft_transformer_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic6_ft_transformer_exp_seed1.sh --name mimic6_ft_transformer_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic6_ft_transformer_exp_seed2.sh --name mimic6_ft_transformer_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic6_ft_transformer_exp_seed3.sh --name mimic6_ft_transformer_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic6_ft_transformer_exp_seed4.sh --name mimic6_ft_transformer_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic6_mlp_exp_seed0.sh --name mimic6_mlp_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic6_mlp_exp_seed1.sh --name mimic6_mlp_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic6_mlp_exp_seed2.sh --name mimic6_mlp_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic6_mlp_exp_seed3.sh --name mimic6_mlp_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic6_mlp_exp_seed4.sh --name mimic6_mlp_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic6_resnet_exp_seed0.sh --name mimic6_resnet_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic6_resnet_exp_seed1.sh --name mimic6_resnet_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic6_resnet_exp_seed2.sh --name mimic6_resnet_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic6_resnet_exp_seed3.sh --name mimic6_resnet_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic6_resnet_exp_seed4.sh --name mimic6_resnet_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic6_tab_transformer_exp_seed0.sh --name mimic6_tab_transformer_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic6_tab_transformer_exp_seed1.sh --name mimic6_tab_transformer_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic6_tab_transformer_exp_seed2.sh --name mimic6_tab_transformer_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic6_tab_transformer_exp_seed3.sh --name mimic6_tab_transformer_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic6_tab_transformer_exp_seed4.sh --name mimic6_tab_transformer_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic7_ft_transformer_exp_seed0.sh --name mimic7_ft_transformer_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic7_ft_transformer_exp_seed1.sh --name mimic7_ft_transformer_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic7_ft_transformer_exp_seed2.sh --name mimic7_ft_transformer_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic7_ft_transformer_exp_seed3.sh --name mimic7_ft_transformer_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic7_ft_transformer_exp_seed4.sh --name mimic7_ft_transformer_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic7_mlp_exp_seed0.sh --name mimic7_mlp_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic7_mlp_exp_seed1.sh --name mimic7_mlp_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic7_mlp_exp_seed2.sh --name mimic7_mlp_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic7_mlp_exp_seed3.sh --name mimic7_mlp_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic7_mlp_exp_seed4.sh --name mimic7_mlp_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic7_resnet_exp_seed0.sh --name mimic7_resnet_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic7_resnet_exp_seed1.sh --name mimic7_resnet_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic7_resnet_exp_seed2.sh --name mimic7_resnet_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic7_resnet_exp_seed3.sh --name mimic7_resnet_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic7_resnet_exp_seed4.sh --name mimic7_resnet_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic7_tab_transformer_exp_seed0.sh --name mimic7_tab_transformer_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic7_tab_transformer_exp_seed1.sh --name mimic7_tab_transformer_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic7_tab_transformer_exp_seed2.sh --name mimic7_tab_transformer_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic7_tab_transformer_exp_seed3.sh --name mimic7_tab_transformer_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic7_tab_transformer_exp_seed4.sh --name mimic7_tab_transformer_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic8_ft_transformer_exp_seed0.sh --name mimic8_ft_transformer_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic8_ft_transformer_exp_seed1.sh --name mimic8_ft_transformer_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic8_ft_transformer_exp_seed2.sh --name mimic8_ft_transformer_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic8_ft_transformer_exp_seed3.sh --name mimic8_ft_transformer_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic8_ft_transformer_exp_seed4.sh --name mimic8_ft_transformer_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic8_mlp_exp_seed0.sh --name mimic8_mlp_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic8_mlp_exp_seed1.sh --name mimic8_mlp_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic8_mlp_exp_seed2.sh --name mimic8_mlp_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic8_mlp_exp_seed3.sh --name mimic8_mlp_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic8_mlp_exp_seed4.sh --name mimic8_mlp_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic8_resnet_exp_seed0.sh --name mimic8_resnet_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic8_resnet_exp_seed1.sh --name mimic8_resnet_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic8_resnet_exp_seed2.sh --name mimic8_resnet_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic8_resnet_exp_seed3.sh --name mimic8_resnet_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic8_resnet_exp_seed4.sh --name mimic8_resnet_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic8_tab_transformer_exp_seed0.sh --name mimic8_tab_transformer_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic8_tab_transformer_exp_seed1.sh --name mimic8_tab_transformer_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic8_tab_transformer_exp_seed2.sh --name mimic8_tab_transformer_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic8_tab_transformer_exp_seed3.sh --name mimic8_tab_transformer_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic8_tab_transformer_exp_seed4.sh --name mimic8_tab_transformer_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic9_ft_transformer_exp_seed0.sh --name mimic9_ft_transformer_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic9_ft_transformer_exp_seed1.sh --name mimic9_ft_transformer_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic9_ft_transformer_exp_seed2.sh --name mimic9_ft_transformer_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic9_ft_transformer_exp_seed3.sh --name mimic9_ft_transformer_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic9_ft_transformer_exp_seed4.sh --name mimic9_ft_transformer_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic9_mlp_exp_seed0.sh --name mimic9_mlp_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic9_mlp_exp_seed1.sh --name mimic9_mlp_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic9_mlp_exp_seed2.sh --name mimic9_mlp_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic9_mlp_exp_seed3.sh --name mimic9_mlp_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic9_mlp_exp_seed4.sh --name mimic9_mlp_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic9_resnet_exp_seed0.sh --name mimic9_resnet_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic9_resnet_exp_seed1.sh --name mimic9_resnet_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic9_resnet_exp_seed2.sh --name mimic9_resnet_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic9_resnet_exp_seed3.sh --name mimic9_resnet_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic9_resnet_exp_seed4.sh --name mimic9_resnet_exp_seed4 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic9_tab_transformer_exp_seed0.sh --name mimic9_tab_transformer_exp_seed0 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic9_tab_transformer_exp_seed1.sh --name mimic9_tab_transformer_exp_seed1 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic9_tab_transformer_exp_seed2.sh --name mimic9_tab_transformer_exp_seed2 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic9_tab_transformer_exp_seed3.sh --name mimic9_tab_transformer_exp_seed3 --time 72
python3 dispatch_single_node.py launch/tuned_deep_jobs/mimic9_tab_transformer_exp_seed4.sh --name mimic9_tab_transformer_exp_seed4 --time 72
