program = "bin/catboost_mimic_.py"

[base_config]
seed = 0

[base_config.data]
cat_policy = "indices"
dset_id = 'mimic'
task = "binclass"

[base_config.model]
early_stopping_rounds = 50
iterations = 1000
metric_period = 10
od_pval = 0.001
task_type = "GPU"
thread_count = 1

[base_config.fit]
logging_level = "Verbose"

[base_config.transfer]
stage = "pretrain"
load_checkpoint = false
checkpoint_path = nan
pretrain_proportion = 0
downstream_samples_per_class = 10
freeze_feature_extractor = false
layers_to_fine_tune = []
use_mlp_head = false
epochs_warm_up_head = 0
head_lr = nan
use_optuna_CV = false
pretrain_subsample = true

[optimization.options]
n_trials = 50

[optimization.sampler]
seed = 0

[optimization.space.model]
bagging_temperature = [ "uniform", 0.0, 1.0,]
depth = [ "int", 6, 10,]
l2_leaf_reg = [ "loguniform", 1.0, 10.0,]
leaf_estimation_iterations = [ "int", 1, 10,]
learning_rate = [ "loguniform", 1e-5, 1,]