seed = 0

[data]
cat_policy = 'indices'
dset_id = 541
normalization = 'quantile'
task = 'regression'
y_policy = 'mean_std'

[model]
activation = 'reglu'
attention_dropout = 0.0145522011297429
d_ffn_factor = 0.9384489267447308
d_token = 288
ffn_dropout = 0.04510346984923107
initialization = 'kaiming'
n_heads = 8
n_layers = 2
prenormalization = true
residual_dropout = 0.0

[training]
batch_size = 256
eval_batch_size = 8192
lr = 9.200592579617476e-05
lr_n_decays = 0
n_epochs = 500
num_batch_warm_up = 0
optimizer = 'adamw'
patience = 30
weight_decay = 2.259125904388358e-06

[transfer]
checkpoint_path = nan
downstream_samples_per_class = nan
epochs_warm_up_head = 0
freeze_feature_extractor = false
head_lr = nan
layers_to_fine_tune = []
load_checkpoint = false
pretrain_proportion = 0.5
stage = 'pretrain'
use_mlp_head = false
