seed = 0

[data]
cat_policy = 'indices'
dset_id = 188
normalization = 'quantile'
task = 'multiclass'

[model]
activation = 'reglu'
attention_dropout = 0.220831253414288
d_ffn_factor = 2.122541352384976
d_token = 368
ffn_dropout = 0.07373175276982377
initialization = 'kaiming'
n_heads = 8
n_layers = 3
prenormalization = true
residual_dropout = 0.06812690374868036

[training]
batch_size = 256
eval_batch_size = 8192
lr = 0.0005477957043364873
lr_n_decays = 0
n_epochs = 500
num_batch_warm_up = 0
optimizer = 'adamw'
patience = 30
weight_decay = 5.30931130337387e-06

[transfer]
checkpoint_path = nan
downstream_samples_per_class = nan
epochs_warm_up_head = 0
freeze_feature_extractor = false
head_lr = nan
layers_to_fine_tune = []
load_checkpoint = false
pretrain_proportion = 0.5
stage = 'pretrain'
use_mlp_head = false
