python dispatch_single_node.py launch/tuned_deep_jobs/1483_mlp_exp_seed0.sh --time 24 --name 1483_mlp_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/1483_mlp_exp_seed1.sh --time 24 --name 1483_mlp_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/1483_mlp_exp_seed2.sh --time 24 --name 1483_mlp_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/1483_mlp_exp_seed3.sh --time 24 --name 1483_mlp_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/1483_mlp_exp_seed4.sh --time 24 --name 1483_mlp_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/1483_resnet_exp_seed0.sh --time 24 --name 1483_resnet_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/1483_resnet_exp_seed1.sh --time 24 --name 1483_resnet_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/1483_resnet_exp_seed2.sh --time 24 --name 1483_resnet_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/1483_resnet_exp_seed3.sh --time 24 --name 1483_resnet_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/1483_resnet_exp_seed4.sh --time 24 --name 1483_resnet_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/1483_saint_exp_seed0.sh --time 24 --name 1483_saint_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/1483_saint_exp_seed1.sh --time 24 --name 1483_saint_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/1483_saint_exp_seed2.sh --time 24 --name 1483_saint_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/1483_saint_exp_seed3.sh --time 24 --name 1483_saint_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/1483_saint_exp_seed4.sh --time 24 --name 1483_saint_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/188_mlp_exp_seed0.sh --time 24 --name 188_mlp_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/188_mlp_exp_seed1.sh --time 24 --name 188_mlp_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/188_mlp_exp_seed2.sh --time 24 --name 188_mlp_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/188_mlp_exp_seed3.sh --time 24 --name 188_mlp_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/188_mlp_exp_seed4.sh --time 24 --name 188_mlp_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/188_resnet_exp_seed0.sh --time 24 --name 188_resnet_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/188_resnet_exp_seed1.sh --time 24 --name 188_resnet_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/188_resnet_exp_seed2.sh --time 24 --name 188_resnet_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/188_resnet_exp_seed3.sh --time 24 --name 188_resnet_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/188_resnet_exp_seed4.sh --time 24 --name 188_resnet_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/188_saint_exp_seed0.sh --time 24 --name 188_saint_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/188_saint_exp_seed1.sh --time 24 --name 188_saint_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/188_saint_exp_seed2.sh --time 24 --name 188_saint_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/188_saint_exp_seed3.sh --time 24 --name 188_saint_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/188_saint_exp_seed4.sh --time 24 --name 188_saint_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/40687_mlp_exp_seed0.sh --time 24 --name 40687_mlp_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/40687_mlp_exp_seed1.sh --time 24 --name 40687_mlp_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/40687_mlp_exp_seed2.sh --time 24 --name 40687_mlp_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/40687_mlp_exp_seed3.sh --time 24 --name 40687_mlp_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/40687_mlp_exp_seed4.sh --time 24 --name 40687_mlp_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/40687_resnet_exp_seed0.sh --time 24 --name 40687_resnet_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/40687_resnet_exp_seed1.sh --time 24 --name 40687_resnet_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/40687_resnet_exp_seed2.sh --time 24 --name 40687_resnet_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/40687_resnet_exp_seed3.sh --time 24 --name 40687_resnet_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/40687_resnet_exp_seed4.sh --time 24 --name 40687_resnet_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/40687_saint_exp_seed0.sh --time 24 --name 40687_saint_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/40687_saint_exp_seed1.sh --time 24 --name 40687_saint_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/40687_saint_exp_seed2.sh --time 24 --name 40687_saint_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/40687_saint_exp_seed3.sh --time 24 --name 40687_saint_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/40687_saint_exp_seed4.sh --time 24 --name 40687_saint_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/40975_mlp_exp_seed0.sh --time 24 --name 40975_mlp_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/40975_mlp_exp_seed1.sh --time 24 --name 40975_mlp_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/40975_mlp_exp_seed2.sh --time 24 --name 40975_mlp_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/40975_mlp_exp_seed3.sh --time 24 --name 40975_mlp_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/40975_mlp_exp_seed4.sh --time 24 --name 40975_mlp_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/40975_resnet_exp_seed0.sh --time 24 --name 40975_resnet_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/40975_resnet_exp_seed1.sh --time 24 --name 40975_resnet_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/40975_resnet_exp_seed2.sh --time 24 --name 40975_resnet_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/40975_resnet_exp_seed3.sh --time 24 --name 40975_resnet_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/40975_resnet_exp_seed4.sh --time 24 --name 40975_resnet_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/40975_saint_exp_seed0.sh --time 24 --name 40975_saint_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/40975_saint_exp_seed1.sh --time 24 --name 40975_saint_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/40975_saint_exp_seed2.sh --time 24 --name 40975_saint_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/40975_saint_exp_seed3.sh --time 24 --name 40975_saint_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/40975_saint_exp_seed4.sh --time 24 --name 40975_saint_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/41169_mlp_exp_seed0.sh --time 24 --name 41169_mlp_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/41169_mlp_exp_seed1.sh --time 24 --name 41169_mlp_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/41169_mlp_exp_seed2.sh --time 24 --name 41169_mlp_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/41169_mlp_exp_seed3.sh --time 24 --name 41169_mlp_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/41169_mlp_exp_seed4.sh --time 24 --name 41169_mlp_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/41169_resnet_exp_seed0.sh --time 24 --name 41169_resnet_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/41169_resnet_exp_seed1.sh --time 24 --name 41169_resnet_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/41169_resnet_exp_seed2.sh --time 24 --name 41169_resnet_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/41169_resnet_exp_seed3.sh --time 24 --name 41169_resnet_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/41169_resnet_exp_seed4.sh --time 24 --name 41169_resnet_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/41169_saint_exp_seed0.sh --time 24 --name 41169_saint_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/41169_saint_exp_seed1.sh --time 24 --name 41169_saint_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/41169_saint_exp_seed2.sh --time 24 --name 41169_saint_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/41169_saint_exp_seed3.sh --time 24 --name 41169_saint_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/41169_saint_exp_seed4.sh --time 24 --name 41169_saint_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/42726_mlp_exp_seed0.sh --time 24 --name 42726_mlp_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/42726_mlp_exp_seed1.sh --time 24 --name 42726_mlp_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/42726_mlp_exp_seed2.sh --time 24 --name 42726_mlp_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/42726_mlp_exp_seed3.sh --time 24 --name 42726_mlp_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/42726_mlp_exp_seed4.sh --time 24 --name 42726_mlp_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/42726_resnet_exp_seed0.sh --time 24 --name 42726_resnet_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/42726_resnet_exp_seed1.sh --time 24 --name 42726_resnet_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/42726_resnet_exp_seed2.sh --time 24 --name 42726_resnet_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/42726_resnet_exp_seed3.sh --time 24 --name 42726_resnet_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/42726_resnet_exp_seed4.sh --time 24 --name 42726_resnet_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/42726_saint_exp_seed0.sh --time 24 --name 42726_saint_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/42726_saint_exp_seed1.sh --time 24 --name 42726_saint_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/42726_saint_exp_seed2.sh --time 24 --name 42726_saint_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/42726_saint_exp_seed3.sh --time 24 --name 42726_saint_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/42726_saint_exp_seed4.sh --time 24 --name 42726_saint_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/42728_mlp_exp_seed0.sh --time 24 --name 42728_mlp_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/42728_mlp_exp_seed1.sh --time 24 --name 42728_mlp_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/42728_mlp_exp_seed2.sh --time 24 --name 42728_mlp_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/42728_mlp_exp_seed3.sh --time 24 --name 42728_mlp_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/42728_mlp_exp_seed4.sh --time 24 --name 42728_mlp_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/42728_resnet_exp_seed0.sh --time 24 --name 42728_resnet_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/42728_resnet_exp_seed1.sh --time 24 --name 42728_resnet_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/42728_resnet_exp_seed2.sh --time 24 --name 42728_resnet_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/42728_resnet_exp_seed3.sh --time 24 --name 42728_resnet_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/42728_resnet_exp_seed4.sh --time 24 --name 42728_resnet_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/42728_saint_exp_seed0.sh --time 24 --name 42728_saint_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/42728_saint_exp_seed1.sh --time 24 --name 42728_saint_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/42728_saint_exp_seed2.sh --time 24 --name 42728_saint_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/42728_saint_exp_seed3.sh --time 24 --name 42728_saint_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/42728_saint_exp_seed4.sh --time 24 --name 42728_saint_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/541_mlp_exp_seed0.sh --time 24 --name 541_mlp_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/541_mlp_exp_seed1.sh --time 24 --name 541_mlp_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/541_mlp_exp_seed2.sh --time 24 --name 541_mlp_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/541_mlp_exp_seed3.sh --time 24 --name 541_mlp_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/541_mlp_exp_seed4.sh --time 24 --name 541_mlp_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/541_resnet_exp_seed0.sh --time 24 --name 541_resnet_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/541_resnet_exp_seed1.sh --time 24 --name 541_resnet_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/541_resnet_exp_seed2.sh --time 24 --name 541_resnet_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/541_resnet_exp_seed3.sh --time 24 --name 541_resnet_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/541_resnet_exp_seed4.sh --time 24 --name 541_resnet_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/541_saint_exp_seed0.sh --time 24 --name 541_saint_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/541_saint_exp_seed1.sh --time 24 --name 541_saint_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/541_saint_exp_seed2.sh --time 24 --name 541_saint_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/541_saint_exp_seed3.sh --time 24 --name 541_saint_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/541_saint_exp_seed4.sh --time 24 --name 541_saint_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/california_housing_mlp_exp_seed0.sh --time 24 --name california_housing_mlp_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/california_housing_mlp_exp_seed1.sh --time 24 --name california_housing_mlp_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/california_housing_mlp_exp_seed2.sh --time 24 --name california_housing_mlp_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/california_housing_mlp_exp_seed3.sh --time 24 --name california_housing_mlp_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/california_housing_mlp_exp_seed4.sh --time 24 --name california_housing_mlp_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/california_housing_resnet_exp_seed0.sh --time 24 --name california_housing_resnet_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/california_housing_resnet_exp_seed1.sh --time 24 --name california_housing_resnet_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/california_housing_resnet_exp_seed2.sh --time 24 --name california_housing_resnet_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/california_housing_resnet_exp_seed3.sh --time 24 --name california_housing_resnet_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/california_housing_resnet_exp_seed4.sh --time 24 --name california_housing_resnet_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/california_housing_saint_exp_seed0.sh --time 24 --name california_housing_saint_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/california_housing_saint_exp_seed1.sh --time 24 --name california_housing_saint_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/california_housing_saint_exp_seed2.sh --time 24 --name california_housing_saint_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/california_housing_saint_exp_seed3.sh --time 24 --name california_housing_saint_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/california_housing_saint_exp_seed4.sh --time 24 --name california_housing_saint_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/jannis_mlp_exp_seed0.sh --time 24 --name jannis_mlp_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/jannis_mlp_exp_seed1.sh --time 24 --name jannis_mlp_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/jannis_mlp_exp_seed2.sh --time 24 --name jannis_mlp_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/jannis_mlp_exp_seed3.sh --time 24 --name jannis_mlp_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/jannis_mlp_exp_seed4.sh --time 24 --name jannis_mlp_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/jannis_resnet_exp_seed0.sh --time 24 --name jannis_resnet_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/jannis_resnet_exp_seed1.sh --time 24 --name jannis_resnet_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/jannis_resnet_exp_seed2.sh --time 24 --name jannis_resnet_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/jannis_resnet_exp_seed3.sh --time 24 --name jannis_resnet_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/jannis_resnet_exp_seed4.sh --time 24 --name jannis_resnet_exp_seed4
python dispatch_single_node.py launch/tuned_deep_jobs/jannis_saint_exp_seed0.sh --time 24 --name jannis_saint_exp_seed0
python dispatch_single_node.py launch/tuned_deep_jobs/jannis_saint_exp_seed1.sh --time 24 --name jannis_saint_exp_seed1
python dispatch_single_node.py launch/tuned_deep_jobs/jannis_saint_exp_seed2.sh --time 24 --name jannis_saint_exp_seed2
python dispatch_single_node.py launch/tuned_deep_jobs/jannis_saint_exp_seed3.sh --time 24 --name jannis_saint_exp_seed3
python dispatch_single_node.py launch/tuned_deep_jobs/jannis_saint_exp_seed4.sh --time 24 --name jannis_saint_exp_seed4