python dispatch_single_node.py launch/default_catboost_jobs/1483_catboost_exp_seed0.sh --name 1483_catboost_exp_seed0 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/1483_catboost_exp_seed1.sh --name 1483_catboost_exp_seed1 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/1483_catboost_exp_seed2.sh --name 1483_catboost_exp_seed2 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/1483_catboost_exp_seed3.sh --name 1483_catboost_exp_seed3 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/1483_catboost_exp_seed4.sh --name 1483_catboost_exp_seed4 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/188_catboost_exp_seed0.sh --name 188_catboost_exp_seed0 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/188_catboost_exp_seed1.sh --name 188_catboost_exp_seed1 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/188_catboost_exp_seed2.sh --name 188_catboost_exp_seed2 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/188_catboost_exp_seed3.sh --name 188_catboost_exp_seed3 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/188_catboost_exp_seed4.sh --name 188_catboost_exp_seed4 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/40687_catboost_exp_seed0.sh --name 40687_catboost_exp_seed0 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/40687_catboost_exp_seed1.sh --name 40687_catboost_exp_seed1 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/40687_catboost_exp_seed2.sh --name 40687_catboost_exp_seed2 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/40687_catboost_exp_seed3.sh --name 40687_catboost_exp_seed3 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/40687_catboost_exp_seed4.sh --name 40687_catboost_exp_seed4 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/40975_catboost_exp_seed0.sh --name 40975_catboost_exp_seed0 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/40975_catboost_exp_seed1.sh --name 40975_catboost_exp_seed1 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/40975_catboost_exp_seed2.sh --name 40975_catboost_exp_seed2 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/40975_catboost_exp_seed3.sh --name 40975_catboost_exp_seed3 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/40975_catboost_exp_seed4.sh --name 40975_catboost_exp_seed4 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/41169_catboost_exp_seed0.sh --name 41169_catboost_exp_seed0 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/41169_catboost_exp_seed1.sh --name 41169_catboost_exp_seed1 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/41169_catboost_exp_seed2.sh --name 41169_catboost_exp_seed2 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/41169_catboost_exp_seed3.sh --name 41169_catboost_exp_seed3 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/41169_catboost_exp_seed4.sh --name 41169_catboost_exp_seed4 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/42726_catboost_exp_seed0.sh --name 42726_catboost_exp_seed0 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/42726_catboost_exp_seed1.sh --name 42726_catboost_exp_seed1 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/42726_catboost_exp_seed2.sh --name 42726_catboost_exp_seed2 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/42726_catboost_exp_seed3.sh --name 42726_catboost_exp_seed3 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/42726_catboost_exp_seed4.sh --name 42726_catboost_exp_seed4 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/42728_catboost_exp_seed0.sh --name 42728_catboost_exp_seed0 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/42728_catboost_exp_seed1.sh --name 42728_catboost_exp_seed1 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/42728_catboost_exp_seed2.sh --name 42728_catboost_exp_seed2 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/42728_catboost_exp_seed3.sh --name 42728_catboost_exp_seed3 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/42728_catboost_exp_seed4.sh --name 42728_catboost_exp_seed4 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/541_catboost_exp_seed0.sh --name 541_catboost_exp_seed0 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/541_catboost_exp_seed1.sh --name 541_catboost_exp_seed1 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/541_catboost_exp_seed2.sh --name 541_catboost_exp_seed2 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/541_catboost_exp_seed3.sh --name 541_catboost_exp_seed3 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/541_catboost_exp_seed4.sh --name 541_catboost_exp_seed4 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/california_housing_catboost_exp_seed0.sh --name california_housing_catboost_exp_seed0 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/california_housing_catboost_exp_seed1.sh --name california_housing_catboost_exp_seed1 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/california_housing_catboost_exp_seed2.sh --name california_housing_catboost_exp_seed2 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/california_housing_catboost_exp_seed3.sh --name california_housing_catboost_exp_seed3 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/california_housing_catboost_exp_seed4.sh --name california_housing_catboost_exp_seed4 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/jannis_catboost_exp_seed0.sh --name jannis_catboost_exp_seed0 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/jannis_catboost_exp_seed1.sh --name jannis_catboost_exp_seed1 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/jannis_catboost_exp_seed2.sh --name jannis_catboost_exp_seed2 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/jannis_catboost_exp_seed3.sh --name jannis_catboost_exp_seed3 --time 8
python dispatch_single_node.py launch/default_catboost_jobs/jannis_catboost_exp_seed4.sh --name jannis_catboost_exp_seed4 --time 8
