seed = 0

[data]
cat_policy = 'ohe'
dset_id = 188
task = 'multiclass'

[fit]
early_stopping_rounds = 50
verbose = false

[model]
alpha = 0
booster = 'gbtree'
colsample_bylevel = 0.738832558660675
colsample_bytree = 0.9060843643877465
gamma = 0
lambda = 0
learning_rate = 0.0009202884691104544
max_depth = 4
min_child_weight = 8.384337589822227e-08
n_estimators = 2000
n_jobs = -1
subsample = 0.5435646498507704
tree_method = 'gpu_hist'

[transfer]
checkpoint_path = nan
downstream_samples_per_class = nan
epochs_warm_up_head = 0
freeze_feature_extractor = false
head_lr = nan
layers_to_fine_tune = []
load_checkpoint = false
pretrain_proportion = 0.5
stage = 'pretrain'
use_mlp_head = false
