python dispatch_single_node.py launch/tuned_xgboost_jobs/1483_xgboost_exp_seed0.sh --time 12 --name 1483_xgboost_exp_seed0
python dispatch_single_node.py launch/tuned_xgboost_jobs/1483_xgboost_exp_seed1.sh --time 12 --name 1483_xgboost_exp_seed1
python dispatch_single_node.py launch/tuned_xgboost_jobs/1483_xgboost_exp_seed2.sh --time 12 --name 1483_xgboost_exp_seed2
python dispatch_single_node.py launch/tuned_xgboost_jobs/1483_xgboost_exp_seed3.sh --time 12 --name 1483_xgboost_exp_seed3
python dispatch_single_node.py launch/tuned_xgboost_jobs/1483_xgboost_exp_seed4.sh --time 12 --name 1483_xgboost_exp_seed4
python dispatch_single_node.py launch/tuned_xgboost_jobs/188_xgboost_exp_seed0.sh --time 12 --name 188_xgboost_exp_seed0
python dispatch_single_node.py launch/tuned_xgboost_jobs/188_xgboost_exp_seed1.sh --time 12 --name 188_xgboost_exp_seed1
python dispatch_single_node.py launch/tuned_xgboost_jobs/188_xgboost_exp_seed2.sh --time 12 --name 188_xgboost_exp_seed2
python dispatch_single_node.py launch/tuned_xgboost_jobs/188_xgboost_exp_seed3.sh --time 12 --name 188_xgboost_exp_seed3
python dispatch_single_node.py launch/tuned_xgboost_jobs/188_xgboost_exp_seed4.sh --time 12 --name 188_xgboost_exp_seed4
python dispatch_single_node.py launch/tuned_xgboost_jobs/40687_xgboost_exp_seed0.sh --time 12 --name 40687_xgboost_exp_seed0
python dispatch_single_node.py launch/tuned_xgboost_jobs/40687_xgboost_exp_seed1.sh --time 12 --name 40687_xgboost_exp_seed1
python dispatch_single_node.py launch/tuned_xgboost_jobs/40687_xgboost_exp_seed2.sh --time 12 --name 40687_xgboost_exp_seed2
python dispatch_single_node.py launch/tuned_xgboost_jobs/40687_xgboost_exp_seed3.sh --time 12 --name 40687_xgboost_exp_seed3
python dispatch_single_node.py launch/tuned_xgboost_jobs/40687_xgboost_exp_seed4.sh --time 12 --name 40687_xgboost_exp_seed4
python dispatch_single_node.py launch/tuned_xgboost_jobs/40975_xgboost_exp_seed0.sh --time 12 --name 40975_xgboost_exp_seed0
python dispatch_single_node.py launch/tuned_xgboost_jobs/40975_xgboost_exp_seed1.sh --time 12 --name 40975_xgboost_exp_seed1
python dispatch_single_node.py launch/tuned_xgboost_jobs/40975_xgboost_exp_seed2.sh --time 12 --name 40975_xgboost_exp_seed2
python dispatch_single_node.py launch/tuned_xgboost_jobs/40975_xgboost_exp_seed3.sh --time 12 --name 40975_xgboost_exp_seed3
python dispatch_single_node.py launch/tuned_xgboost_jobs/40975_xgboost_exp_seed4.sh --time 12 --name 40975_xgboost_exp_seed4
python dispatch_single_node.py launch/tuned_xgboost_jobs/41169_xgboost_exp_seed0.sh --time 12 --name 41169_xgboost_exp_seed0
python dispatch_single_node.py launch/tuned_xgboost_jobs/41169_xgboost_exp_seed1.sh --time 12 --name 41169_xgboost_exp_seed1
python dispatch_single_node.py launch/tuned_xgboost_jobs/41169_xgboost_exp_seed2.sh --time 12 --name 41169_xgboost_exp_seed2
python dispatch_single_node.py launch/tuned_xgboost_jobs/41169_xgboost_exp_seed3.sh --time 12 --name 41169_xgboost_exp_seed3
python dispatch_single_node.py launch/tuned_xgboost_jobs/41169_xgboost_exp_seed4.sh --time 12 --name 41169_xgboost_exp_seed4
python dispatch_single_node.py launch/tuned_xgboost_jobs/42726_xgboost_exp_seed0.sh --time 12 --name 42726_xgboost_exp_seed0
python dispatch_single_node.py launch/tuned_xgboost_jobs/42726_xgboost_exp_seed1.sh --time 12 --name 42726_xgboost_exp_seed1
python dispatch_single_node.py launch/tuned_xgboost_jobs/42726_xgboost_exp_seed2.sh --time 12 --name 42726_xgboost_exp_seed2
python dispatch_single_node.py launch/tuned_xgboost_jobs/42726_xgboost_exp_seed3.sh --time 12 --name 42726_xgboost_exp_seed3
python dispatch_single_node.py launch/tuned_xgboost_jobs/42726_xgboost_exp_seed4.sh --time 12 --name 42726_xgboost_exp_seed4
python dispatch_single_node.py launch/tuned_xgboost_jobs/42728_xgboost_exp_seed0.sh --time 12 --name 42728_xgboost_exp_seed0
python dispatch_single_node.py launch/tuned_xgboost_jobs/42728_xgboost_exp_seed1.sh --time 12 --name 42728_xgboost_exp_seed1
python dispatch_single_node.py launch/tuned_xgboost_jobs/42728_xgboost_exp_seed2.sh --time 12 --name 42728_xgboost_exp_seed2
python dispatch_single_node.py launch/tuned_xgboost_jobs/42728_xgboost_exp_seed3.sh --time 12 --name 42728_xgboost_exp_seed3
python dispatch_single_node.py launch/tuned_xgboost_jobs/42728_xgboost_exp_seed4.sh --time 12 --name 42728_xgboost_exp_seed4
python dispatch_single_node.py launch/tuned_xgboost_jobs/541_xgboost_exp_seed0.sh --time 12 --name 541_xgboost_exp_seed0
python dispatch_single_node.py launch/tuned_xgboost_jobs/541_xgboost_exp_seed1.sh --time 12 --name 541_xgboost_exp_seed1
python dispatch_single_node.py launch/tuned_xgboost_jobs/541_xgboost_exp_seed2.sh --time 12 --name 541_xgboost_exp_seed2
python dispatch_single_node.py launch/tuned_xgboost_jobs/541_xgboost_exp_seed3.sh --time 12 --name 541_xgboost_exp_seed3
python dispatch_single_node.py launch/tuned_xgboost_jobs/541_xgboost_exp_seed4.sh --time 12 --name 541_xgboost_exp_seed4
python dispatch_single_node.py launch/tuned_xgboost_jobs/california_housing_xgboost_exp_seed0.sh --time 12 --name california_housing_xgboost_exp_seed0
python dispatch_single_node.py launch/tuned_xgboost_jobs/california_housing_xgboost_exp_seed1.sh --time 12 --name california_housing_xgboost_exp_seed1
python dispatch_single_node.py launch/tuned_xgboost_jobs/california_housing_xgboost_exp_seed2.sh --time 12 --name california_housing_xgboost_exp_seed2
python dispatch_single_node.py launch/tuned_xgboost_jobs/california_housing_xgboost_exp_seed3.sh --time 12 --name california_housing_xgboost_exp_seed3
python dispatch_single_node.py launch/tuned_xgboost_jobs/california_housing_xgboost_exp_seed4.sh --time 12 --name california_housing_xgboost_exp_seed4
python dispatch_single_node.py launch/tuned_xgboost_jobs/jannis_xgboost_exp_seed0.sh --time 12 --name jannis_xgboost_exp_seed0
python dispatch_single_node.py launch/tuned_xgboost_jobs/jannis_xgboost_exp_seed1.sh --time 12 --name jannis_xgboost_exp_seed1
python dispatch_single_node.py launch/tuned_xgboost_jobs/jannis_xgboost_exp_seed2.sh --time 12 --name jannis_xgboost_exp_seed2
python dispatch_single_node.py launch/tuned_xgboost_jobs/jannis_xgboost_exp_seed3.sh --time 12 --name jannis_xgboost_exp_seed3
python dispatch_single_node.py launch/tuned_xgboost_jobs/jannis_xgboost_exp_seed4.sh --time 12 --name jannis_xgboost_exp_seed4
