python dispatch_single_node.py launch/tuned_catboost_jobs/1483_catboost_exp_seed0.sh --time 24 --name 1483_catboost_exp_seed0
python dispatch_single_node.py launch/tuned_catboost_jobs/1483_catboost_exp_seed1.sh --time 24 --name 1483_catboost_exp_seed1
python dispatch_single_node.py launch/tuned_catboost_jobs/1483_catboost_exp_seed2.sh --time 24 --name 1483_catboost_exp_seed2
python dispatch_single_node.py launch/tuned_catboost_jobs/1483_catboost_exp_seed3.sh --time 24 --name 1483_catboost_exp_seed3
python dispatch_single_node.py launch/tuned_catboost_jobs/1483_catboost_exp_seed4.sh --time 24 --name 1483_catboost_exp_seed4
python dispatch_single_node.py launch/tuned_catboost_jobs/188_catboost_exp_seed0.sh --time 24 --name 188_catboost_exp_seed0
python dispatch_single_node.py launch/tuned_catboost_jobs/188_catboost_exp_seed1.sh --time 24 --name 188_catboost_exp_seed1
python dispatch_single_node.py launch/tuned_catboost_jobs/188_catboost_exp_seed2.sh --time 24 --name 188_catboost_exp_seed2
python dispatch_single_node.py launch/tuned_catboost_jobs/188_catboost_exp_seed3.sh --time 24 --name 188_catboost_exp_seed3
python dispatch_single_node.py launch/tuned_catboost_jobs/188_catboost_exp_seed4.sh --time 24 --name 188_catboost_exp_seed4
python dispatch_single_node.py launch/tuned_catboost_jobs/40687_catboost_exp_seed0.sh --time 24 --name 40687_catboost_exp_seed0
python dispatch_single_node.py launch/tuned_catboost_jobs/40687_catboost_exp_seed1.sh --time 24 --name 40687_catboost_exp_seed1
python dispatch_single_node.py launch/tuned_catboost_jobs/40687_catboost_exp_seed2.sh --time 24 --name 40687_catboost_exp_seed2
python dispatch_single_node.py launch/tuned_catboost_jobs/40687_catboost_exp_seed3.sh --time 24 --name 40687_catboost_exp_seed3
python dispatch_single_node.py launch/tuned_catboost_jobs/40687_catboost_exp_seed4.sh --time 24 --name 40687_catboost_exp_seed4
python dispatch_single_node.py launch/tuned_catboost_jobs/40975_catboost_exp_seed0.sh --time 24 --name 40975_catboost_exp_seed0
python dispatch_single_node.py launch/tuned_catboost_jobs/40975_catboost_exp_seed1.sh --time 24 --name 40975_catboost_exp_seed1
python dispatch_single_node.py launch/tuned_catboost_jobs/40975_catboost_exp_seed2.sh --time 24 --name 40975_catboost_exp_seed2
python dispatch_single_node.py launch/tuned_catboost_jobs/40975_catboost_exp_seed3.sh --time 24 --name 40975_catboost_exp_seed3
python dispatch_single_node.py launch/tuned_catboost_jobs/40975_catboost_exp_seed4.sh --time 24 --name 40975_catboost_exp_seed4
python dispatch_single_node.py launch/tuned_catboost_jobs/41169_catboost_exp_seed0.sh --time 24 --name 41169_catboost_exp_seed0
python dispatch_single_node.py launch/tuned_catboost_jobs/41169_catboost_exp_seed1.sh --time 24 --name 41169_catboost_exp_seed1
python dispatch_single_node.py launch/tuned_catboost_jobs/41169_catboost_exp_seed2.sh --time 24 --name 41169_catboost_exp_seed2
python dispatch_single_node.py launch/tuned_catboost_jobs/41169_catboost_exp_seed3.sh --time 24 --name 41169_catboost_exp_seed3
python dispatch_single_node.py launch/tuned_catboost_jobs/41169_catboost_exp_seed4.sh --time 24 --name 41169_catboost_exp_seed4
python dispatch_single_node.py launch/tuned_catboost_jobs/42726_catboost_exp_seed0.sh --time 24 --name 42726_catboost_exp_seed0
python dispatch_single_node.py launch/tuned_catboost_jobs/42726_catboost_exp_seed1.sh --time 24 --name 42726_catboost_exp_seed1
python dispatch_single_node.py launch/tuned_catboost_jobs/42726_catboost_exp_seed2.sh --time 24 --name 42726_catboost_exp_seed2
python dispatch_single_node.py launch/tuned_catboost_jobs/42726_catboost_exp_seed3.sh --time 24 --name 42726_catboost_exp_seed3
python dispatch_single_node.py launch/tuned_catboost_jobs/42726_catboost_exp_seed4.sh --time 24 --name 42726_catboost_exp_seed4
python dispatch_single_node.py launch/tuned_catboost_jobs/42728_catboost_exp_seed0.sh --time 24 --name 42728_catboost_exp_seed0
python dispatch_single_node.py launch/tuned_catboost_jobs/42728_catboost_exp_seed1.sh --time 24 --name 42728_catboost_exp_seed1
python dispatch_single_node.py launch/tuned_catboost_jobs/42728_catboost_exp_seed2.sh --time 24 --name 42728_catboost_exp_seed2
python dispatch_single_node.py launch/tuned_catboost_jobs/42728_catboost_exp_seed3.sh --time 24 --name 42728_catboost_exp_seed3
python dispatch_single_node.py launch/tuned_catboost_jobs/42728_catboost_exp_seed4.sh --time 24 --name 42728_catboost_exp_seed4
python dispatch_single_node.py launch/tuned_catboost_jobs/541_catboost_exp_seed0.sh --time 24 --name 541_catboost_exp_seed0
python dispatch_single_node.py launch/tuned_catboost_jobs/541_catboost_exp_seed1.sh --time 24 --name 541_catboost_exp_seed1
python dispatch_single_node.py launch/tuned_catboost_jobs/541_catboost_exp_seed2.sh --time 24 --name 541_catboost_exp_seed2
python dispatch_single_node.py launch/tuned_catboost_jobs/541_catboost_exp_seed3.sh --time 24 --name 541_catboost_exp_seed3
python dispatch_single_node.py launch/tuned_catboost_jobs/541_catboost_exp_seed4.sh --time 24 --name 541_catboost_exp_seed4
python dispatch_single_node.py launch/tuned_catboost_jobs/california_housing_catboost_exp_seed0.sh --time 24 --name california_housing_catboost_exp_seed0
python dispatch_single_node.py launch/tuned_catboost_jobs/california_housing_catboost_exp_seed1.sh --time 24 --name california_housing_catboost_exp_seed1
python dispatch_single_node.py launch/tuned_catboost_jobs/california_housing_catboost_exp_seed2.sh --time 24 --name california_housing_catboost_exp_seed2
python dispatch_single_node.py launch/tuned_catboost_jobs/california_housing_catboost_exp_seed3.sh --time 24 --name california_housing_catboost_exp_seed3
python dispatch_single_node.py launch/tuned_catboost_jobs/california_housing_catboost_exp_seed4.sh --time 24 --name california_housing_catboost_exp_seed4
python dispatch_single_node.py launch/tuned_catboost_jobs/jannis_catboost_exp_seed0.sh --time 24 --name jannis_catboost_exp_seed0
python dispatch_single_node.py launch/tuned_catboost_jobs/jannis_catboost_exp_seed1.sh --time 24 --name jannis_catboost_exp_seed1
python dispatch_single_node.py launch/tuned_catboost_jobs/jannis_catboost_exp_seed2.sh --time 24 --name jannis_catboost_exp_seed2
python dispatch_single_node.py launch/tuned_catboost_jobs/jannis_catboost_exp_seed3.sh --time 24 --name jannis_catboost_exp_seed3
python dispatch_single_node.py launch/tuned_catboost_jobs/jannis_catboost_exp_seed4.sh --time 24 --name jannis_catboost_exp_seed4
