#
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic0_resnet_exp_seed0.sh --name mimic0_resnet_exp_seed0 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic0_resnet_exp_seed1.sh --name mimic0_resnet_exp_seed1 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic0_resnet_exp_seed2.sh --name mimic0_resnet_exp_seed2 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic0_resnet_exp_seed3.sh --name mimic0_resnet_exp_seed3 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic0_resnet_exp_seed4.sh --name mimic0_resnet_exp_seed4 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic1_resnet_exp_seed0.sh --name mimic1_resnet_exp_seed0 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic1_resnet_exp_seed1.sh --name mimic1_resnet_exp_seed1 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic1_resnet_exp_seed2.sh --name mimic1_resnet_exp_seed2 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic1_resnet_exp_seed3.sh --name mimic1_resnet_exp_seed3 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic1_resnet_exp_seed4.sh --name mimic1_resnet_exp_seed4 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic4_resnet_exp_seed0.sh --name mimic4_resnet_exp_seed0 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic4_resnet_exp_seed1.sh --name mimic4_resnet_exp_seed1 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic4_resnet_exp_seed2.sh --name mimic4_resnet_exp_seed2 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic4_resnet_exp_seed3.sh --name mimic4_resnet_exp_seed3 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic4_resnet_exp_seed4.sh --name mimic4_resnet_exp_seed4 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic5_resnet_exp_seed0.sh --name mimic5_resnet_exp_seed0 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic5_resnet_exp_seed1.sh --name mimic5_resnet_exp_seed1 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic5_resnet_exp_seed2.sh --name mimic5_resnet_exp_seed2 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic5_resnet_exp_seed3.sh --name mimic5_resnet_exp_seed3 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic5_resnet_exp_seed4.sh --name mimic5_resnet_exp_seed4 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic0_ft_transformer_exp_seed0.sh --name mimic0_ft_transformer_exp_seed0 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic0_ft_transformer_exp_seed1.sh --name mimic0_ft_transformer_exp_seed1 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic0_ft_transformer_exp_seed2.sh --name mimic0_ft_transformer_exp_seed2 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic0_ft_transformer_exp_seed3.sh --name mimic0_ft_transformer_exp_seed3 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic0_ft_transformer_exp_seed4.sh --name mimic0_ft_transformer_exp_seed4 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic1_ft_transformer_exp_seed0.sh --name mimic1_ft_transformer_exp_seed0 --time 5
python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic1_ft_transformer_exp_seed1.sh --name mimic1_ft_transformer_exp_seed1 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic1_ft_transformer_exp_seed2.sh --name mimic1_ft_transformer_exp_seed2 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic1_ft_transformer_exp_seed3.sh --name mimic1_ft_transformer_exp_seed3 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic1_ft_transformer_exp_seed4.sh --name mimic1_ft_transformer_exp_seed4 --time 5
python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic4_ft_transformer_exp_seed0.sh --name mimic4_ft_transformer_exp_seed0 --time 5
python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic4_ft_transformer_exp_seed1.sh --name mimic4_ft_transformer_exp_seed1 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic4_ft_transformer_exp_seed2.sh --name mimic4_ft_transformer_exp_seed2 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic4_ft_transformer_exp_seed3.sh --name mimic4_ft_transformer_exp_seed3 --time 5
python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic4_ft_transformer_exp_seed4.sh --name mimic4_ft_transformer_exp_seed4 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic5_ft_transformer_exp_seed0.sh --name mimic5_ft_transformer_exp_seed0 --time 5
python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic5_ft_transformer_exp_seed1.sh --name mimic5_ft_transformer_exp_seed1 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic5_ft_transformer_exp_seed2.sh --name mimic5_ft_transformer_exp_seed2 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic5_ft_transformer_exp_seed3.sh --name mimic5_ft_transformer_exp_seed3 --time 5
#python3 dispatch_single_node.py launch_mimic_dev/deep_dwnstrm_default_standard/mimic5_ft_transformer_exp_seed4.sh --name mimic5_ft_transformer_exp_seed4 --time 5