program = 'bin/resnet.py'

[base_config]
seed = 0

	[base_config.data]
	dset_id = 188 # id of openml dataset
	task = 'multiclass' # can be binclass, multiclass, regression
	cat_policy = 'indices'
	normalization = 'quantile'

	[base_config.model]
	activation = 'relu'
	normalization = 'batchnorm'

	[base_config.training]
	batch_size = 256
	eval_batch_size = 8192
	n_epochs = 500
	optimizer = 'adamw'
	patience = 30
	lr_n_decays = 0
	num_batch_warm_up = 0


	[base_config.transfer]
	stage = 'pretrain'
	load_checkpoint = false
	checkpoint_path = nan
	pretrain_proportion = 0.5
	downstream_samples_per_class = nan
	freeze_feature_extractor = false
	layers_to_fine_tune = []
	use_mlp_head = false
	epochs_warm_up_head = 0
	head_lr = nan


[optimization.options]
n_trials = 50

[optimization.sampler]
seed = 0

[optimization.space.model]
d = [ 'int', 64, 512 ]
d_embedding = ['int', 64, 512]
d_hidden_factor = [ 'uniform', 1.0, 4.0 ]
hidden_dropout = [ 'uniform', 0.0, 0.5 ]
n_layers = [ 'int', 1, 8 ]
residual_dropout = [ '?uniform', 0.0, 0.0, 0.5 ]

[optimization.space.training]
lr = [ 'loguniform', 1e-05, 0.01 ]
weight_decay = [ '?loguniform', 0.0, 1e-06, 0.001 ]

