seed = 0

[data]
cat_policy = 'indices'
dset_id = 188
normalization = 'quantile'
task = 'multiclass'

[model]
d_embedding = 350
d_layers = [ 511, 511, 511, 512 ]
dropout = 0.0

[training]
batch_size = 256
eval_batch_size = 8192
lr = 0.00918892148631417
lr_n_decays = 0
n_epochs = 500
num_batch_warm_up = 0
optimizer = 'adamw'
patience = 30
weight_decay = 0.0

[transfer]
checkpoint_path = nan
downstream_samples_per_class = nan
epochs_warm_up_head = 0
freeze_feature_extractor = false
head_lr = nan
layers_to_fine_tune = []
load_checkpoint = false
pretrain_proportion = 0.5
stage = 'pretrain'
use_mlp_head = false
