seed = 0

[data]
cat_policy = 'indices'
dset_id = 541
normalization = 'quantile'
task = 'regression'
y_policy = 'mean_std'

[model]
activation = 'relu'
d = 349
d_embedding = 363
d_hidden_factor = 1.918445166190766
hidden_dropout = 0.4651271576668868
n_layers = 7
normalization = 'batchnorm'
residual_dropout = 0.3582148656885057

[training]
batch_size = 256
eval_batch_size = 8192
lr = 0.006789478543425116
lr_n_decays = 0
n_epochs = 500
num_batch_warm_up = 0
optimizer = 'adamw'
patience = 30
weight_decay = 1.086863819260209e-06

[transfer]
checkpoint_path = nan
downstream_samples_per_class = nan
epochs_warm_up_head = 0
freeze_feature_extractor = false
head_lr = nan
layers_to_fine_tune = []
load_checkpoint = false
pretrain_proportion = 0.5
stage = 'pretrain'
use_mlp_head = false
