seed = 0

[data]
cat_policy = 'indices'
dset_id = 'california_housing'
normalization = 'quantile'
task = 'regression'
y_policy = 'mean_std'

[model]
attentiontype = 'colrow'
attn_dropout = 0.7851001553863802
cont_embeddings = 'MLP'
depth = 1
embed_dim = 12
ff_dropout = 0.5532867218108045
final_mlp_style = 'sep'
heads = 6
use_cls = true

[training]
batch_size = 352
lr = 0.0007726043442171304
lr_n_decays = 0
n_epochs = 500
num_batch_warm_up = 0
optimizer = 'adamw'
patience = 30
weight_decay = 0.0005097575837524329

[transfer]
checkpoint_path = nan
downstream_samples_per_class = nan
epochs_warm_up_head = 0
freeze_feature_extractor = false
head_lr = nan
layers_to_fine_tune = []
load_checkpoint = false
pretrain_proportion = 0.5
stage = 'pretrain'
use_mlp_head = false
