seed = 0

[data]
cat_policy = 'indices'
dset_id = 40975
normalization = 'quantile'
task = 'multiclass'

[model]
attentiontype = 'colrow'
attn_dropout = 0.5292881023563949
cont_embeddings = 'MLP'
depth = 1
embed_dim = 125
ff_dropout = 0.7065594491486105
final_mlp_style = 'sep'
heads = 5
use_cls = true

[training]
batch_size = 323
lr = 0.0004948840736375751
lr_n_decays = 0
n_epochs = 500
num_batch_warm_up = 0
optimizer = 'adamw'
patience = 30
weight_decay = 7.424908231815009e-05

[transfer]
checkpoint_path = nan
downstream_samples_per_class = nan
epochs_warm_up_head = 0
freeze_feature_extractor = false
head_lr = nan
layers_to_fine_tune = []
load_checkpoint = false
pretrain_proportion = 0.5
stage = 'pretrain'
use_mlp_head = false
