seed = 0

[data]
cat_policy = 'indices'
dset_id = 40975
normalization = 'quantile'
task = 'multiclass'

[model]
activation = 'reglu'
attention_dropout = 0.08065475894249813
d_ffn_factor = 1.972883317597463
d_token = 384
ffn_dropout = 0.2071842941131844
initialization = 'kaiming'
n_heads = 8
n_layers = 1
prenormalization = true
residual_dropout = 0.1247020202263737

[training]
batch_size = 256
eval_batch_size = 8192
lr = 4.742586160938567e-05
lr_n_decays = 0
n_epochs = 500
num_batch_warm_up = 0
optimizer = 'adamw'
patience = 30
weight_decay = 0.0001057443000344446

[transfer]
checkpoint_path = nan
downstream_samples_per_class = nan
epochs_warm_up_head = 0
freeze_feature_extractor = false
head_lr = nan
layers_to_fine_tune = []
load_checkpoint = false
pretrain_proportion = 0.5
stage = 'pretrain'
use_mlp_head = false
