program = 'bin/tab_transformer.py'

[base_config]
seed = 0

	[base_config.data]
	dset_id = 'california_housing' # id of openml dataset
	task = 'regression' # can be binclass, regression, regression
	cat_policy = 'indices'
	normalization = 'quantile'
	y_policy = 'mean_std'

	[base_config.model]
	dim_head = 16
	mlp_hidden_mults = [4, 2]


	[base_config.transfer]
	stage = 'pretrain'
	load_checkpoint = false
	checkpoint_path = nan
	pretrain_proportion = 0.5
	downstream_samples_per_class = nan
	freeze_feature_extractor = false
	layers_to_fine_tune = []
	use_mlp_head = false
	epochs_warm_up_head = 0
	head_lr = nan


	[base_config.training]
	batch_size = 256
	eval_batch_size = 8192
	lr_n_decays = 0
	n_epochs = 500
	optimizer = 'adamw'
	patience = 30
	num_batch_warm_up = 0

[optimization.options]
n_trials = 30

[optimization.sampler]
seed = 0


[optimization.space.model]
heads = ['int', 2, 8]
dim = ['int', 32, 256]
depth = ['int', 1, 12]
attn_dropout = [ 'uniform', 0.0, 0.5]
ff_dropout = [ 'uniform', 0.0, 0.5]

[optimization.space.training]
lr = [ 'loguniform', 1e-05, 0.001]
weight_decay = [ 'loguniform', 1e-06, 0.001]

