seed = 0

[data]
cat_policy = 'indices'
dset_id = 541
normalization = 'quantile'
task = 'regression'
y_policy = 'mean_std'

[model]
d_embedding = 380
d_layers = [ 174, 32, 32, 32, 32, 219 ]
dropout = 0.0

[training]
batch_size = 256
eval_batch_size = 8192
lr = 0.009768508548091444
lr_n_decays = 0
n_epochs = 500
num_batch_warm_up = 0
optimizer = 'adamw'
patience = 30
weight_decay = 0.0

[transfer]
checkpoint_path = nan
downstream_samples_per_class = nan
epochs_warm_up_head = 0
freeze_feature_extractor = false
head_lr = nan
layers_to_fine_tune = []
load_checkpoint = false
pretrain_proportion = 0.5
stage = 'pretrain'
use_mlp_head = false
