seed = 0

[data]
cat_policy = 'indices'
dset_id = 'california_housing'
normalization = 'quantile'
task = 'regression'
y_policy = 'mean_std'

[model]
activation = 'relu'
d = 443
d_embedding = 454
d_hidden_factor = 1.619518023274083
hidden_dropout = 0.4264390308822956
n_layers = 3
normalization = 'batchnorm'
residual_dropout = 0.0

[training]
batch_size = 256
eval_batch_size = 8192
lr = 0.000290440720997032
lr_n_decays = 0
n_epochs = 500
num_batch_warm_up = 0
optimizer = 'adamw'
patience = 30
weight_decay = 0.0

[transfer]
checkpoint_path = nan
downstream_samples_per_class = nan
epochs_warm_up_head = 0
freeze_feature_extractor = false
head_lr = nan
layers_to_fine_tune = []
load_checkpoint = false
pretrain_proportion = 0.5
stage = 'pretrain'
use_mlp_head = false
