python3 bin/tune.py optuna_configs/188/saint/0.toml -f
python3 bin/tune.py optuna_configs/541/saint/0.toml -f
python3 bin/tune.py optuna_configs/1483/saint/0.toml -f
python3 bin/tune.py optuna_configs/40687/saint/0.toml -f
python3 bin/tune.py optuna_configs/40975/saint/0.toml -f
python3 bin/tune.py optuna_configs/41166/saint/0.toml -f
python3 bin/tune.py optuna_configs/41169/saint/0.toml -f
python3 bin/tune.py optuna_configs/42726/saint/0.toml -f
python3 bin/tune.py optuna_configs/42728/saint/0.toml -f
python3 bin/tune.py optuna_configs/california_housing/saint/0.toml -f
python3 bin/tune.py optuna_configs/jannis/saint/0.toml -f
python3 bin/tune.py optuna_configs/year/saint/0.toml -f