seed = 0

[data]
cat_policy = 'indices'
dset_id = 1483
normalization = 'quantile'
task = 'multiclass'

[model]
attentiontype = 'colrow'
attn_dropout = 0.6286258125173247
cont_embeddings = 'MLP'
depth = 1
embed_dim = 21
ff_dropout = 0.2460655463038132
final_mlp_style = 'sep'
heads = 5
use_cls = true

[training]
batch_size = 155
lr = 0.0003336774202794609
lr_n_decays = 0
n_epochs = 500
num_batch_warm_up = 0
optimizer = 'adamw'
patience = 30
weight_decay = 3.996229336691772e-05

[transfer]
checkpoint_path = nan
downstream_samples_per_class = nan
epochs_warm_up_head = 0
freeze_feature_extractor = false
head_lr = nan
layers_to_fine_tune = []
load_checkpoint = false
pretrain_proportion = 0.5
stage = 'pretrain'
use_mlp_head = false
