seed = 0

[data]
cat_policy = 'indices'
dset_id = 188
normalization = 'quantile'
task = 'multiclass'

[model]
attentiontype = 'colrow'
attn_dropout = 0.7742930953718279
cont_embeddings = 'MLP'
depth = 1
embed_dim = 87
ff_dropout = 0.7220072889480915
final_mlp_style = 'sep'
heads = 4
use_cls = true

[training]
batch_size = 227
lr = 0.0003965675081771009
lr_n_decays = 0
n_epochs = 500
num_batch_warm_up = 0
optimizer = 'adamw'
patience = 30
weight_decay = 2.423472448467594e-05

[transfer]
checkpoint_path = nan
downstream_samples_per_class = nan
epochs_warm_up_head = 0
freeze_feature_extractor = false
head_lr = nan
layers_to_fine_tune = []
load_checkpoint = false
pretrain_proportion = 0.5
stage = 'pretrain'
use_mlp_head = false
