seed = 0

[data]
cat_policy = 'indices'
dset_id = 1483
normalization = 'quantile'
task = 'multiclass'

[model]
activation = 'relu'
d = 501
d_embedding = 237
d_hidden_factor = 3.447095793118831
hidden_dropout = 0.2226054179891289
n_layers = 5
normalization = 'batchnorm'
residual_dropout = 0.07491801401023987

[training]
batch_size = 256
eval_batch_size = 8192
lr = 0.001422728391511961
lr_n_decays = 0
n_epochs = 500
num_batch_warm_up = 0
optimizer = 'adamw'
patience = 30
weight_decay = 1.017057459893185e-05

[transfer]
checkpoint_path = nan
downstream_samples_per_class = nan
epochs_warm_up_head = 0
freeze_feature_extractor = false
head_lr = nan
layers_to_fine_tune = []
load_checkpoint = false
pretrain_proportion = 0.5
stage = 'pretrain'
use_mlp_head = false
