python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_saint_0.sh --name saint_0_mimic --time 72 --gpus 2
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_saint_10.sh --name saint_10_mimic --time 72 --gpus 2
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_saint_11.sh --name saint_11_mimic --time 72 --gpus 2
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_saint_1.sh --name saint_1_mimic --time 72 --gpus 2
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_saint_2.sh --name saint_2_mimic --time 72 --gpus 2
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_saint_3.sh --name saint_3_mimic --time 72 --gpus 2
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_saint_4.sh --name saint_4_mimic --time 72 --gpus 2
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_saint_5.sh --name saint_5_mimic --time 72 --gpus 2
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_saint_6.sh --name saint_6_mimic --time 72 --gpus 2
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_saint_7.sh --name saint_7_mimic --time 72 --gpus 2
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_saint_8.sh --name saint_8_mimic --time 72 --gpus 2
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_saint_9.sh --name saint_9_mimic --time 72 --gpus 2