python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_1483_catboost.sh --name 1483_catboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_1483_xgboost.sh --name 1483_xgboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_1596_catboost.sh --name 1596_catboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_1596_xgboost.sh --name 1596_xgboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_188_catboost.sh --name 188_catboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_188_xgboost.sh --name 188_xgboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_40687_catboost.sh --name 40687_catboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_40687_xgboost.sh --name 40687_xgboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_40975_catboost.sh --name 40975_catboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_40975_xgboost.sh --name 40975_xgboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_41166_catboost.sh --name 41166_catboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_41166_xgboost.sh --name 41166_xgboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_41169_catboost.sh --name 41169_catboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_41169_xgboost.sh --name 41169_xgboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_42726_catboost.sh --name 42726_catboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_42726_xgboost.sh --name 42726_xgboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_42728_catboost.sh --name 42728_catboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_42728_xgboost.sh --name 42728_xgboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_43172_catboost.sh --name 43172_catboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_43172_xgboost.sh --name 43172_xgboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_541_catboost.sh --name 541_catboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_541_xgboost.sh --name 541_xgboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_554_catboost.sh --name 554_catboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_554_xgboost.sh --name 554_xgboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_california_housing_catboost.sh --name california_housing_catboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_california_housing_xgboost.sh --name california_housing_xgboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_jannis_catboost.sh --name jannis_catboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_jannis_xgboost.sh --name jannis_xgboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_year_catboost.sh --name year_catboost --time 24
python3 dispatch_single_node.py  launch/optuna_jobs/boost/optuning_year_xgboost.sh --name year_xgboost --time 24
