python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_ft_transformer_0.sh --name ft_transformer_0_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_ft_transformer_10.sh --name ft_transformer_10_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_ft_transformer_11.sh --name ft_transformer_11_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_ft_transformer_1.sh --name ft_transformer_1_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_ft_transformer_2.sh --name ft_transformer_2_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_ft_transformer_3.sh --name ft_transformer_3_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_ft_transformer_4.sh --name ft_transformer_4_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_ft_transformer_5.sh --name ft_transformer_5_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_ft_transformer_6.sh --name ft_transformer_6_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_ft_transformer_7.sh --name ft_transformer_7_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_ft_transformer_8.sh --name ft_transformer_8_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_ft_transformer_9.sh --name ft_transformer_9_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_mlp_0.sh --name mlp_0_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_mlp_10.sh --name mlp_10_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_mlp_11.sh --name mlp_11_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_mlp_1.sh --name mlp_1_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_mlp_2.sh --name mlp_2_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_mlp_3.sh --name mlp_3_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_mlp_4.sh --name mlp_4_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_mlp_5.sh --name mlp_5_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_mlp_6.sh --name mlp_6_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_mlp_7.sh --name mlp_7_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_mlp_8.sh --name mlp_8_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_mlp_9.sh --name mlp_9_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_resnet_0.sh --name resnet_0_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_resnet_10.sh --name resnet_10_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_resnet_11.sh --name resnet_11_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_resnet_1.sh --name resnet_1_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_resnet_2.sh --name resnet_2_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_resnet_3.sh --name resnet_3_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_resnet_4.sh --name resnet_4_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_resnet_5.sh --name resnet_5_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_resnet_6.sh --name resnet_6_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_resnet_7.sh --name resnet_7_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_resnet_8.sh --name resnet_8_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_resnet_9.sh --name resnet_9_mimic --time 72
#python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_saint_0.sh --name saint_0_mimic --time 72
#python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_saint_10.sh --name saint_10_mimic --time 72
#python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_saint_11.sh --name saint_11_mimic --time 72
#python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_saint_1.sh --name saint_1_mimic --time 72
#python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_saint_2.sh --name saint_2_mimic --time 72
#python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_saint_3.sh --name saint_3_mimic --time 72
#python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_saint_4.sh --name saint_4_mimic --time 72
#python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_saint_5.sh --name saint_5_mimic --time 72
#python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_saint_6.sh --name saint_6_mimic --time 72
#python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_saint_7.sh --name saint_7_mimic --time 72
#python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_saint_8.sh --name saint_8_mimic --time 72
#python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_saint_9.sh --name saint_9_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_tab_transformer_0.sh --name tab_transformer_0_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_tab_transformer_10.sh --name tab_transformer_10_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_tab_transformer_11.sh --name tab_transformer_11_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_tab_transformer_1.sh --name tab_transformer_1_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_tab_transformer_2.sh --name tab_transformer_2_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_tab_transformer_3.sh --name tab_transformer_3_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_tab_transformer_4.sh --name tab_transformer_4_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_tab_transformer_5.sh --name tab_transformer_5_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_tab_transformer_6.sh --name tab_transformer_6_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_tab_transformer_7.sh --name tab_transformer_7_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_tab_transformer_8.sh --name tab_transformer_8_mimic --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_mimic_tab_transformer_9.sh --name tab_transformer_9_mimic --time 72
