python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_1483_ft_transformer.sh --name 1483_ft_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_1483_mlp.sh --name 1483_mlp --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_1483_resnet.sh --name 1483_resnet --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_1483_saint.sh --name 1483_saint --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_1483_tab_transformer.sh --name 1483_tab_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_1596_ft_transformer.sh --name 1596_ft_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_1596_mlp.sh --name 1596_mlp --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_1596_resnet.sh --name 1596_resnet --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_1596_saint.sh --name 1596_saint --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_1596_tab_transformer.sh --name 1596_tab_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_188_ft_transformer.sh --name 188_ft_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_188_mlp.sh --name 188_mlp --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_188_resnet.sh --name 188_resnet --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_188_saint.sh --name 188_saint --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_188_tab_transformer.sh --name 188_tab_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_40687_ft_transformer.sh --name 40687_ft_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_40687_mlp.sh --name 40687_mlp --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_40687_resnet.sh --name 40687_resnet --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_40687_saint.sh --name 40687_saint --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_40687_tab_transformer.sh --name 40687_tab_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_40975_ft_transformer.sh --name 40975_ft_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_40975_mlp.sh --name 40975_mlp --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_40975_resnet.sh --name 40975_resnet --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_40975_saint.sh --name 40975_saint --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_40975_tab_transformer.sh --name 40975_tab_transformer --time 72
#python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_41166_ft_transformer.sh --name 41166_ft_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_41166_mlp.sh --name 41166_mlp --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_41166_resnet.sh --name 41166_resnet --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_41166_saint.sh --name 41166_saint --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_41166_tab_transformer.sh --name 41166_tab_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_41169_ft_transformer.sh --name 41169_ft_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_41169_mlp.sh --name 41169_mlp --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_41169_resnet.sh --name 41169_resnet --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_41169_saint.sh --name 41169_saint --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_41169_tab_transformer.sh --name 41169_tab_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_42726_ft_transformer.sh --name 42726_ft_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_42726_mlp.sh --name 42726_mlp --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_42726_resnet.sh --name 42726_resnet --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_42726_saint.sh --name 42726_saint --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_42726_tab_transformer.sh --name 42726_tab_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_42728_ft_transformer.sh --name 42728_ft_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_42728_mlp.sh --name 42728_mlp --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_42728_resnet.sh --name 42728_resnet --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_42728_saint.sh --name 42728_saint --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_42728_tab_transformer.sh --name 42728_tab_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_43172_ft_transformer.sh --name 43172_ft_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_43172_mlp.sh --name 43172_mlp --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_43172_resnet.sh --name 43172_resnet --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_43172_saint.sh --name 43172_saint --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_43172_tab_transformer.sh --name 43172_tab_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_541_ft_transformer.sh --name 541_ft_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_541_mlp.sh --name 541_mlp --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_541_resnet.sh --name 541_resnet --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_541_saint.sh --name 541_saint --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_541_tab_transformer.sh --name 541_tab_transformer --time 72
#python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_554_ft_transformer.sh --name 554_ft_transformer --time 72
#python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_554_mlp.sh --name 554_mlp --time 72
#python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_554_resnet.sh --name 554_resnet --time 72
#python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_554_saint.sh --name 554_saint --time 72
#python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_554_tab_transformer.sh --name 554_tab_transformer --time 72
#python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_aloi_ft_transformer.sh --name aloi_ft_transformer --time 72
#python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_aloi_mlp.sh --name aloi_mlp --time 72
#python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_aloi_resnet.sh --name aloi_resnet --time 72
#python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_aloi_saint.sh --name aloi_saint --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_aloi_tab_transformer.sh --name aloi_tab_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_california_housing_ft_transformer.sh --name california_housing_ft_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_california_housing_mlp.sh --name california_housing_mlp --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_california_housing_resnet.sh --name california_housing_resnet --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_california_housing_saint.sh --name california_housing_saint --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_california_housing_tab_transformer.sh --name california_housing_tab_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_jannis_ft_transformer.sh --name jannis_ft_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_jannis_mlp.sh --name jannis_mlp --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_jannis_resnet.sh --name jannis_resnet --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_jannis_saint.sh --name jannis_saint --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_jannis_tab_transformer.sh --name jannis_tab_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_year_ft_transformer.sh --name year_ft_transformer --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_year_mlp.sh --name year_mlp --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_year_resnet.sh --name year_resnet --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_year_saint.sh --name year_saint --time 72
python3 dispatch_single_node.py launch/optuna_jobs/deep/optuning_year_tab_transformer.sh --name year_tab_transformer --time 72
