seed = 0

[data]
cat_policy = 'indices'
dset_id = 188
normalization = 'quantile'
task = 'multiclass'

[model]
activation = 'relu'
d = 399
d_embedding = 495
d_hidden_factor = 3.610261775075309
hidden_dropout = 0.2368040226368552
n_layers = 2
normalization = 'batchnorm'
residual_dropout = 0.2602387397756024

[training]
batch_size = 256
eval_batch_size = 8192
lr = 0.001088024288293846
lr_n_decays = 0
n_epochs = 500
num_batch_warm_up = 0
optimizer = 'adamw'
patience = 30
weight_decay = 8.313101133778734e-05

[transfer]
checkpoint_path = nan
downstream_samples_per_class = nan
epochs_warm_up_head = 0
freeze_feature_extractor = false
head_lr = nan
layers_to_fine_tune = []
load_checkpoint = false
pretrain_proportion = 0.5
stage = 'pretrain'
use_mlp_head = false
