seed = 0

[data]
cat_policy = 'ohe'
dset_id = 42726
task = 'regression'
y_policy = 'mean_std'

[fit]
early_stopping_rounds = 50
verbose = false

[model]
alpha = 1.067037935726317
booster = 'gbtree'
colsample_bylevel = 0.990690927752191
colsample_bytree = 0.6401336051051523
gamma = 0
lambda = 0
learning_rate = 0.5366593111959473
max_depth = 3
min_child_weight = 1.759629473977968
n_estimators = 2000
n_jobs = -1
subsample = 0.9539233543764344
tree_method = 'gpu_hist'

[transfer]
checkpoint_path = nan
downstream_samples_per_class = nan
epochs_warm_up_head = 0
freeze_feature_extractor = false
head_lr = nan
layers_to_fine_tune = []
load_checkpoint = false
pretrain_proportion = 0.5
stage = 'pretrain'
use_mlp_head = false
