version: 1
formatters:
  simple:
    format: "[%(asctime)s %(levelname)s]: %(message)s"
    datefmt: "%m/%d/%Y %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: log.log
root:
  handlers: [console, file]

disable_existing_loggers: false
