seed = 0

[data]
cat_policy = 'indices'
dset_id = 42728
normalization = 'quantile'
task = 'regression'
y_policy = 'mean_std'

[model]
attentiontype = 'colrow'
attn_dropout = 0.3262295366443045
cont_embeddings = 'MLP'
depth = 1
embed_dim = 99
ff_dropout = 0.6504116847310738
final_mlp_style = 'sep'
heads = 5
use_cls = true

[training]
batch_size = 181
lr = 4.467807553356729e-05
lr_n_decays = 0
n_epochs = 500
num_batch_warm_up = 0
optimizer = 'adamw'
patience = 30
weight_decay = 1.303996060699816e-06

[transfer]
checkpoint_path = nan
downstream_samples_per_class = nan
epochs_warm_up_head = 0
freeze_feature_extractor = false
head_lr = nan
layers_to_fine_tune = []
load_checkpoint = false
pretrain_proportion = 0.5
stage = 'pretrain'
use_mlp_head = false
