program = 'bin/catboost_.py'

[base_config]
seed = 0

    [base_config.data]
    dset_id = 42728 # id of openml dataset
	task = 'regression' # can be binclass, multiclass, regression
	cat_policy = 'indices'
	y_policy = 'mean_std'

    [base_config.fit]
    logging_level = 'Verbose'

    [base_config.model]
    early_stopping_rounds = 50
    iterations = 2000
    metric_period = 10
    od_pval = 0.001
    task_type = 'GPU'
    thread_count = 1

    [base_config.transfer]
	stage = 'pretrain'
	load_checkpoint = false
	checkpoint_path = nan
	pretrain_proportion = 0.5
	downstream_samples_per_class = nan
	freeze_feature_extractor = false
	layers_to_fine_tune = []
	use_mlp_head = false
	epochs_warm_up_head = 0
	head_lr = nan

[optimization.options]
n_trials = 30

[optimization.sampler]
seed = 0

[optimization.space.model]
bagging_temperature = [ 'uniform', 0.0, 1.0 ]
depth = [ 'int', 3, 10 ]
l2_leaf_reg = [ 'loguniform', 1.0, 10.0 ]
leaf_estimation_iterations = [ 'int', 1, 10 ]
learning_rate = [ 'loguniform', 1e-05, 1 ]