seed = 0

[data]
cat_policy = 'indices'
dset_id = 42728
normalization = 'quantile'
task = 'regression'
y_policy = 'mean_std'

[model]
d_embedding = 192
d_layers = [ 335, 191, 191, 191, 472 ]
dropout = 0.3078612909374209

[training]
batch_size = 256
eval_batch_size = 8192
lr = 0.0006524849737180779
lr_n_decays = 0
n_epochs = 500
num_batch_warm_up = 0
optimizer = 'adamw'
patience = 30
weight_decay = 1.007825907510453e-06

[transfer]
checkpoint_path = nan
downstream_samples_per_class = nan
epochs_warm_up_head = 0
freeze_feature_extractor = false
head_lr = nan
layers_to_fine_tune = []
load_checkpoint = false
pretrain_proportion = 0.5
stage = 'pretrain'
use_mlp_head = false
