seed = 0

[data]
cat_policy = "indices"
dset_id = 'mimic'
normalization = "quantile"
task = "binclass"

[fit]
logging_level = 'Verbose'

[model]
bagging_temperature = 0.5488135039273248
depth = 6
early_stopping_rounds = 50
iterations = 300
l2_leaf_reg = 4.006483661964395
leaf_estimation_iterations = 4
learning_rate = 0.172289453696094
metric_period = 10
od_pval = 0.001
task_type = 'GPU'
thread_count = 1


[transfer]
checkpoint_path = nan
downstream_samples_per_class = 10
epochs_warm_up_head = 0
freeze_feature_extractor = false
head_lr = nan
layers_to_fine_tune = []
load_checkpoint = false
pretrain_proportion = 0
stage = "pretrain"
use_mlp_head = false
use_optuna_CV = false
pretrain_subsample = true
