seed = 0

[data]
cat_policy = 'ohe'
dset_id = 41169
task = 'multiclass'

[fit]
early_stopping_rounds = 50
verbose = false

[model]
alpha = 1.770210973136099
booster = 'gbtree'
colsample_bylevel = 0.506903922867894
colsample_bytree = 0.881080480177563
gamma = 0
lambda = 0
learning_rate = 0.2171668112610259
max_depth = 9
min_child_weight = 0.05378111847734465
n_estimators = 2000
n_jobs = -1
subsample = 0.9397774624936246
tree_method = 'gpu_hist'

[transfer]
checkpoint_path = nan
downstream_samples_per_class = nan
epochs_warm_up_head = 0
freeze_feature_extractor = false
head_lr = nan
layers_to_fine_tune = []
load_checkpoint = false
pretrain_proportion = 0.5
stage = 'pretrain'
use_mlp_head = false
