seed = 0

[data]
cat_policy = 'indices'
dset_id = 40687
task = 'multiclass'

[fit]
logging_level = 'Verbose'

[model]
bagging_temperature = 0.3927847961008297
depth = 4
early_stopping_rounds = 50
iterations = 2000
l2_leaf_reg = 1.177703750752171
leaf_estimation_iterations = 10
learning_rate = 0.01741242906721999
metric_period = 10
od_pval = 0.001
task_type = 'GPU'
thread_count = 1

[transfer]
checkpoint_path = nan
downstream_samples_per_class = nan
epochs_warm_up_head = 0
freeze_feature_extractor = false
head_lr = nan
layers_to_fine_tune = []
load_checkpoint = false
pretrain_proportion = 0.5
stage = 'pretrain'
use_mlp_head = false
