seed = 0

[data]
cat_policy = 'indices'
dset_id = 42726
normalization = 'quantile'
task = 'regression'
y_policy = 'mean_std'

[model]
attentiontype = 'colrow'
attn_dropout = 0.6933468430822605
cont_embeddings = 'MLP'
depth = 1
embed_dim = 117
ff_dropout = 0.6540301800624491
final_mlp_style = 'sep'
heads = 6
use_cls = true

[training]
batch_size = 232
lr = 0.000342053573509555
lr_n_decays = 0
n_epochs = 500
num_batch_warm_up = 0
optimizer = 'adamw'
patience = 30
weight_decay = 1.018335058568103e-06

[transfer]
checkpoint_path = nan
downstream_samples_per_class = nan
epochs_warm_up_head = 0
freeze_feature_extractor = false
head_lr = nan
layers_to_fine_tune = []
load_checkpoint = false
pretrain_proportion = 0.5
stage = 'pretrain'
use_mlp_head = false
