seed = 0

[data]
cat_policy = 'ohe'
dset_id = 40687
task = 'multiclass'

[fit]
early_stopping_rounds = 50
verbose = false

[model]
alpha = 0
booster = 'gbtree'
colsample_bylevel = 0.6182621840271347
colsample_bytree = 0.8256347499271653
gamma = 0
lambda = 0
learning_rate = 1.252962121409724e-05
max_depth = 6
min_child_weight = 4.519030929463992e-05
n_estimators = 2000
n_jobs = -1
subsample = 0.5167340652730485
tree_method = 'gpu_hist'

[transfer]
checkpoint_path = nan
downstream_samples_per_class = nan
epochs_warm_up_head = 0
freeze_feature_extractor = false
head_lr = nan
layers_to_fine_tune = []
load_checkpoint = false
pretrain_proportion = 0.5
stage = 'pretrain'
use_mlp_head = false
